theme: jekyll-theme-architect
title: The Daily App
description: A simple app to send daily emails containing selected subject lines. Also, sends weather info for location and will soon have more features.

